# .air.toml

# Watch these directories and restart the process if any file changes
[watcher]
dirs = ["."]

# Entrypoint file, `main.go` in this case
[build]
cmd = "go"
args = ["run", "main.go"]

# Specify environment variables if needed
[env]
PORT = 8080
